name: Backend build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Set up PostgreSQL
      env:
        ENGINE: django.db.backends.postgresql
        NAME: moviegram
        DB_USER: postgres  # Update this with your PostgreSQL username
        DB_PASSWORD: postgres  # Update this with your PostgreSQL password
        HOST: localhost
        PORT: 5432
        ENVIRONMENT: testing  # Set the environment variable to 'testing'
        Debug: True
        Allowed_Hosts: '*'
      run: |
        sudo service postgresql start  # Start PostgreSQL service
        sudo psql -U $DB_USER -c "CREATE DATABASE $NAME;"  # Create PostgreSQL database
        python3 --version
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r backend/requirements.txt
        python3 backend/manage.py makemigrations
        python3 backend/manage.py migrate
        export DJANGO_SECRET_KEY="$(base64 <<< "$RANDOM|TeStiNg|$RANDOM" | tr -d '\n')"

    - name: Run tests
      env:
        ENGINE: django.db.backends.postgresql
        NAME: moviegram
        DB_USER: postgres
        DB_PASSWORD: postgres
        
      run: |
        source venv/bin/activate
        python3 backend/manage.py test moviegram
